#!/bin/bash

# Commit and push environment variable improvements
echo "🚀 Committing environment variable configuration improvements..."

# Add all changes
git add .

# Commit with comprehensive message
git commit -m "feat(config): Complete environment variable configuration

✅ Environment Variables Added:
- BACKEND_HOST, BACKEND_PORT for backend URL configuration
- FRONTEND_HOST, FRONTEND_PORT for frontend URL configuration  
- USE_HTTPS for protocol switching
- TEST_API_URL for test configurations
- CORS_ALLOWED_ORIGINS environment-driven

🔧 Files Updated:
- backend/apps/management/commands/initialize_platform.py
- backend/apps/learning/management/commands/populate_jac_curriculum.py
- backend/config/settings.py & settings_minimal.py
- backend/test_predictive_analytics.py
- backend/docs/REAL_TIME_MONITORING_GUIDE.md
- frontend/src/setupProxy.js (new file)
- frontend/package.json (proxy removed)
- .env.example (URL configuration added)

🎯 Benefits:
- Environment flexibility (dev/staging/production)
- No hardcoded URLs in source code
- Docker & Kubernetes ready
- CI/CD pipeline integration
- Security improvements

📋 New .env variables documented in ENVIRONMENT_VARIABLES_GUIDE.md

🤖 Generated by MiniMax Agent"

# Push to GitHub
echo "📡 Pushing to GitHub..."
git push origin main

echo "✅ Environment variable configuration complete!"
echo ""
echo "📋 Summary of improvements:"
echo "  ✅ All hardcoded URLs replaced with environment variables"
echo "  ✅ Management commands use environment-driven URLs"
echo "  ✅ CORS configuration is environment-aware"
echo "  ✅ Frontend proxy respects environment variables"
echo "  ✅ Test files use configurable base URLs"
echo "  ✅ Documentation uses dynamic URLs"
echo "  ✅ Comprehensive environment variable guide created"
echo ""
echo "🌟 Your application is now fully environment-configurable!"
echo "📖 See ENVIRONMENT_VARIABLES_GUIDE.md for usage instructions"