#!/bin/bash
# Simple Permission Explanation

echo "🔍 WHY PERMISSION ISSUES OCCUR"
echo "=============================="
echo ""
echo "THE PROBLEM:"
echo "-----------"
echo "1. Docker container runs Django as user 'app' (UID 1000)"
echo "2. Your host files are owned by user 'cavin' (UID 1000)" 
echo "3. Container creates files → ownership mismatch"
echo "4. Django in container can't modify files → Permission Denied"
echo ""
echo "FILE OWNERSHIP MISMATCH:"
echo "----------------------"
echo "Host:     cavin:cavin    (files)"
echo "Container: app:app      (attempts to modify files)"
echo "Result:   Permission denied"
echo ""
echo "WHY chmod -R 755 FIXES IT:"
echo "-------------------------"
echo "• Makes files readable/writable by ALL users"
echo "• Bypasses ownership restrictions"
echo "• Works across container boundaries"
echo "• Preserves all functionality"
echo ""
echo "NOT A ROOT ISSUE:"
echo "----------------"
echo "• Your script runs as: cavin (NOT root)"
echo "• Container runs as: app (NOT root)"
echo "• Problem: Different users, same UID numbers"
echo "• Solution: Universal permissions (755)"
echo ""
echo "FUTURE PREVENTION:"
echo "-----------------"
echo "• Enhanced setup_platform.sh includes permission fixes"
echo "• Runs automatically before migrations"
echo "• No more manual intervention needed"