# Generated by Django 5.2.8 on 2025-11-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchquery',
            new_name='search_quer_query_50e46f_idx',
            old_name='search_queries_query_idx',
        ),
        migrations.RenameIndex(
            model_name='searchquery',
            new_name='search_quer_created_02141d_idx',
            old_name='search_queries_created_idx',
        ),
        migrations.RenameIndex(
            model_name='searchresult',
            new_name='search_resu_content_0fc25c_idx',
            old_name='search_results_content_idx',
        ),
        migrations.RenameIndex(
            model_name='searchresult',
            new_name='search_resu_query_db242d_idx',
            old_name='search_results_query_idx',
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='clicked_result',
            field=models.CharField(blank=True, help_text='URL or identifier of clicked result', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.CharField(help_text='Search query text', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='results_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of results found'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='content_id',
            field=models.CharField(help_text='ID of the content item', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='description',
            field=models.TextField(blank=True, help_text='Description or summary'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='popularity_score',
            field=models.FloatField(default=0.0, help_text='Popularity score (0-1)'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='query',
            field=models.CharField(help_text='Associated search query', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='relevance_score',
            field=models.FloatField(default=0.0, help_text='Relevance score (0-1)'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='tags',
            field=models.JSONField(default=list, help_text='Tags associated with content'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='title',
            field=models.CharField(help_text='Title of the content', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='url',
            field=models.CharField(help_text='URL to access the content', max_length=500),
        ),
    ]
