# Generated by Django 5.2.8 on 2025-11-25 17:09

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField(help_text='User message')),
                ('response', models.TextField(help_text='Agent response')),
                ('agent_type', models.CharField(choices=[('content_curator', 'Content Curator'), ('quiz_master', 'Quiz Master'), ('evaluator', 'Evaluator'), ('progress_tracker', 'Progress Tracker'), ('motivator', 'Motivator'), ('system_orchestrator', 'System Orchestrator')], default='system_orchestrator', max_length=50)),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('agent', 'Agent Response'), ('system', 'System Message')], default='user', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message metadata')),
                ('feedback_rating', models.PositiveIntegerField(blank=True, help_text='User rating from 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_comment', models.TextField(blank=True, help_text='User feedback comment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('session_type', models.CharField(default='learning', max_length=50)),
                ('learning_path_id', models.UUIDField(blank=True, null=True)),
                ('session_data', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('performance_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'learning_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=100, unique=True)),
                ('agent_type', models.CharField(choices=[('content_curator', 'Content Curator'), ('quiz_master', 'Quiz Master'), ('evaluator', 'Evaluator'), ('progress_tracker', 'Progress Tracker'), ('motivator', 'Motivator'), ('system_orchestrator', 'System Orchestrator')], db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='idle', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'simple_agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleAgentMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('metric_type', models.CharField(max_length=50)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'simple_agent_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('task_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'simple_tasks',
                'ordering': ['-assigned_at', '-priority'],
            },
        ),
    ]
