# Generated by Django 4.2.7 on 2025-11-21 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=100, unique=True)),
                ('agent_type', models.CharField(choices=[('content_curator', 'Content Curator'), ('quiz_master', 'Quiz Master'), ('evaluator', 'Evaluator'), ('progress_tracker', 'Progress Tracker'), ('motivator', 'Motivator'), ('system_orchestrator', 'System Orchestrator')], db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='idle', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simple_agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimpleTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('task_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agents.simpleagent')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simple_tasks',
                'ordering': ['-assigned_at', '-priority'],
                'indexes': [models.Index(fields=['agent', 'status'], name='simple_task_agent_i_11fa64_idx'), models.Index(fields=['task_type'], name='simple_task_task_ty_1c5c11_idx'), models.Index(fields=['priority'], name='simple_task_priorit_473687_idx'), models.Index(fields=['assigned_at'], name='simple_task_assigne_1084b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimpleAgentMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('metric_type', models.CharField(max_length=50)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='agents.simpleagent')),
            ],
            options={
                'db_table': 'simple_agent_metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['agent', 'metric_name'], name='simple_agen_agent_i_3dda5f_idx'), models.Index(fields=['recorded_at'], name='simple_agen_recorde_3fa4de_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='simpleagent',
            index=models.Index(fields=['agent_type'], name='simple_agen_agent_t_8233fd_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleagent',
            index=models.Index(fields=['status'], name='simple_agen_status_b18a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleagent',
            index=models.Index(fields=['is_active'], name='simple_agen_is_acti_48b485_idx'),
        ),
    ]
