# Generated by Django 5.2.8 on 2025-11-25 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simpleagent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='agents_involved',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='agents.simpleagent'),
        ),
        migrations.AddField(
            model_name='simpleagentmetrics',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='agents.simpleagent'),
        ),
        migrations.AddField(
            model_name='simpletask',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agents.simpleagent'),
        ),
        migrations.AddField(
            model_name='simpletask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', 'session_id'], name='chat_messag_user_id_379500_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session_id', 'created_at'], name='chat_messag_session_597c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['agent_type'], name='chat_messag_agent_t_642c69_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['feedback_rating'], name='chat_messag_feedbac_2f1294_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleagent',
            index=models.Index(fields=['agent_type'], name='simple_agen_agent_t_8233fd_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleagent',
            index=models.Index(fields=['status'], name='simple_agen_status_b18a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleagent',
            index=models.Index(fields=['is_active'], name='simple_agen_is_acti_48b485_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['user'], name='learning_se_user_id_b339fb_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['session_type'], name='learning_se_session_3d8e55_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['started_at'], name='learning_se_started_f47896_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleagentmetrics',
            index=models.Index(fields=['agent', 'metric_name'], name='simple_agen_agent_i_3dda5f_idx'),
        ),
        migrations.AddIndex(
            model_name='simpleagentmetrics',
            index=models.Index(fields=['recorded_at'], name='simple_agen_recorde_3fa4de_idx'),
        ),
        migrations.AddIndex(
            model_name='simpletask',
            index=models.Index(fields=['agent', 'status'], name='simple_task_agent_i_11fa64_idx'),
        ),
        migrations.AddIndex(
            model_name='simpletask',
            index=models.Index(fields=['task_type'], name='simple_task_task_ty_1c5c11_idx'),
        ),
        migrations.AddIndex(
            model_name='simpletask',
            index=models.Index(fields=['priority'], name='simple_task_priorit_473687_idx'),
        ),
        migrations.AddIndex(
            model_name='simpletask',
            index=models.Index(fields=['assigned_at'], name='simple_task_assigne_1084b0_idx'),
        ),
    ]
