# Generated by Django 5.2.8 on 2025-11-24 14:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField(help_text='User message')),
                ('response', models.TextField(help_text='Agent response')),
                ('agent_type', models.CharField(choices=[('content_curator', 'Content Curator'), ('quiz_master', 'Quiz Master'), ('evaluator', 'Evaluator'), ('progress_tracker', 'Progress Tracker'), ('motivator', 'Motivator'), ('system_orchestrator', 'System Orchestrator')], default='system_orchestrator', max_length=50)),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('agent', 'Agent Response'), ('system', 'System Message')], default='user', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message metadata')),
                ('feedback_rating', models.PositiveIntegerField(blank=True, help_text='User rating from 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_comment', models.TextField(blank=True, help_text='User feedback comment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'session_id'], name='chat_messag_user_id_379500_idx'), models.Index(fields=['session_id', 'created_at'], name='chat_messag_session_597c4e_idx'), models.Index(fields=['agent_type'], name='chat_messag_agent_t_642c69_idx'), models.Index(fields=['feedback_rating'], name='chat_messag_feedbac_2f1294_idx')],
            },
        ),
    ]
