# Generated by Django 5.2.8 on 2025-11-25 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('interactive', 'Interactive Content'), ('video', 'Video'), ('document', 'Document'), ('code_tutorial', 'Code Tutorial'), ('exercise', 'Exercise')], default='markdown', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('content_data', models.JSONField(default=dict, help_text='Structured content data (markdown, HTML, interactive config, etc.)')),
                ('estimated_duration', models.PositiveIntegerField(default=30, help_text='Estimated time in minutes')),
                ('tags', models.JSONField(default=list, help_text='Content tags for categorization')),
                ('topic', models.CharField(blank=True, help_text='Primary topic/category', max_length=100)),
                ('quality_rating', models.FloatField(blank=True, help_text='Quality rating from 1.0 to 5.0', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
                'db_table': 'learning_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.DurationField(default=0)),
                ('average_completion_rate', models.FloatField(default=0.0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('return_visit_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Analytics',
                'verbose_name_plural': 'Content Analytics',
                'db_table': 'content_analytics',
            },
        ),
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('recommendation_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('recommendation_type', models.CharField(choices=[('personalized', 'Personalized'), ('based_on_progress', 'Progress-based'), ('similar_users', 'Similar users'), ('trending', 'Trending')], default='personalized', max_length=20)),
                ('match_score', models.FloatField(help_text='Match score from 0.0 to 1.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reasoning', models.JSONField(default=dict, help_text='Reasoning behind the recommendation')),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Content Recommendation',
                'verbose_name_plural': 'Content Recommendations',
                'db_table': 'content_recommendations',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
    ]
