# Generated by Django 5.2.8 on 2025-11-25 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Primary module using this content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='learning.module'),
        ),
        migrations.AddField(
            model_name='contentanalytics',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='content.content'),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='content.content'),
        ),
        migrations.AddField(
            model_name='contentrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type'], name='learning_co_content_a79119_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['difficulty_level'], name='learning_co_difficu_4c1553_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['is_published'], name='learning_co_is_publ_601a10_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['topic'], name='learning_co_topic_288ef3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentrecommendation',
            unique_together={('user', 'content', 'recommendation_type')},
        ),
    ]
