# Generated by Django 4.2.7 on 2025-11-21 13:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated duration in hours')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='List of prerequisite module IDs')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='learning-paths/covers/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jac_learning_path',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField(help_text='Main module content in markdown or rich text')),
                ('content_type', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('interactive', 'Interactive Content'), ('jac_code', 'JAC Code Tutorial')], default='markdown', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('difficulty_rating', models.PositiveIntegerField(help_text='Difficulty rating from 1 (easiest) to 5 (hardest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('jac_concepts', models.JSONField(blank=True, default=list, help_text='JAC concepts covered in this module')),
                ('code_examples', models.JSONField(blank=True, default=list)),
                ('has_quiz', models.BooleanField(default=False)),
                ('has_coding_exercise', models.BooleanField(default=False)),
                ('has_visual_demo', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.learningpath')),
            ],
            options={
                'db_table': 'jac_module',
                'ordering': ['learning_path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200)),
                ('test_input', models.JSONField(default=dict)),
                ('expected_output', models.JSONField(default=dict)),
                ('test_description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('points', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='learning.module')),
            ],
            options={
                'db_table': 'jac_test_cases',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('next_module', 'Next Module Recommendation'), ('skill_gap', 'Skill Gap Analysis'), ('review_topic', 'Review Topic Suggestion'), ('challenging_exercise', 'Challenging Exercise')], max_length=30)),
                ('content', models.JSONField(help_text='Recommendation details and reasoning')),
                ('priority_score', models.FloatField(default=0.0, help_text='AI-calculated priority score')),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_acted_upon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.learningpath')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jac_learning_recommendation',
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_id', models.CharField(max_length=100, unique=True)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('jac', 'JAC (Jaseci)'), ('javascript', 'JavaScript')], default='python', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Execution Error'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('execution_result', models.JSONField(blank=True, default=dict)),
                ('ai_feedback', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_agent_id', models.CharField(blank=True, max_length=100)),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='learning.learningpath')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='learning.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jac_code_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_id', models.CharField(max_length=100)),
                ('output', models.TextField(blank=True)),
                ('error_output', models.TextField(blank=True)),
                ('execution_time', models.FloatField()),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='learning.codesubmission')),
            ],
            options={
                'db_table': 'jac_code_execution_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AICodeReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('syntax', 'Syntax Analysis'), ('logic', 'Logic Review'), ('performance', 'Performance Analysis'), ('security', 'Security Assessment'), ('style', 'Code Style'), ('best_practices', 'Best Practices')], max_length=20)),
                ('findings', models.JSONField(default=dict)),
                ('suggestions', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('agent_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to='learning.codesubmission')),
            ],
            options={
                'db_table': 'jac_ai_code_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=20)),
                ('time_spent', models.DurationField(default=0)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('quiz_score', models.PositiveIntegerField(blank=True, null=True)),
                ('coding_score', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jac_user_module_progress',
                'indexes': [models.Index(fields=['user', 'status'], name='jac_user_mo_user_id_629892_idx'), models.Index(fields=['module', 'status'], name='jac_user_mo_module__44df0c_idx'), models.Index(fields=['status', 'last_activity_at'], name='jac_user_mo_status_c4fce7_idx')],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserLearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('current_module_order', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jac_user_learning_path',
                'indexes': [models.Index(fields=['user', 'status'], name='jac_user_le_user_id_f56575_idx'), models.Index(fields=['status', 'last_activity_at'], name='jac_user_le_status_a5b55f_idx')],
                'unique_together': {('user', 'learning_path')},
            },
        ),
        migrations.CreateModel(
            name='PathRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 (poor) to 5 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='learning.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jac_path_rating',
                'indexes': [models.Index(fields=['learning_path', 'rating'], name='jac_path_ra_learnin_df221d_idx')],
                'unique_together': {('user', 'learning_path')},
            },
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['learning_path', 'order'], name='jac_module_learnin_fd0b30_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['difficulty_rating'], name='jac_module_difficu_fd908e_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_published'], name='jac_module_is_publ_612a54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('learning_path', 'order')},
        ),
        migrations.AddIndex(
            model_name='learningrecommendation',
            index=models.Index(fields=['user', 'recommendation_type'], name='jac_learnin_user_id_8171ba_idx'),
        ),
        migrations.AddIndex(
            model_name='learningrecommendation',
            index=models.Index(fields=['user', 'is_dismissed', 'expires_at'], name='jac_learnin_user_id_03bfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['difficulty_level'], name='jac_learnin_difficu_432d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_published'], name='jac_learnin_is_publ_0d4ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_featured'], name='jac_learnin_is_feat_804e85_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['created_at'], name='jac_learnin_created_d9f935_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['user', 'status'], name='jac_code_su_user_id_c9158b_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['language'], name='jac_code_su_languag_36ff49_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['submission_id'], name='jac_code_su_submiss_a25480_idx'),
        ),
        migrations.AddIndex(
            model_name='codeexecutionlog',
            index=models.Index(fields=['execution_id'], name='jac_code_ex_executi_7d939e_idx'),
        ),
        migrations.AddIndex(
            model_name='codeexecutionlog',
            index=models.Index(fields=['submission'], name='jac_code_ex_submiss_3cdcae_idx'),
        ),
    ]
