# Generated by Django 5.2.8 on 2025-11-25 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_assessment_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='learning.assessment'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codeexecutionlog',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='learning.codesubmission'),
        ),
        migrations.AddField(
            model_name='aicodereview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to='learning.codesubmission'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='learningrecommendation',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='learningrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.module'),
        ),
        migrations.AddField(
            model_name='learningrecommendation',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.module'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='learning.module'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_assessment_attempts', to='learning.module'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='learning.module'),
        ),
        migrations.AddField(
            model_name='pathrating',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='pathrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='learning.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_links', to='learning.question'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='learning.module'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='learning.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userassessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='learning.assessment'),
        ),
        migrations.AddField(
            model_name='userassessmentresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_assessment_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlearningpath',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.learningpath'),
        ),
        migrations.AddField(
            model_name='userlearningpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.module'),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='codeexecutionlog',
            index=models.Index(fields=['execution_id'], name='jac_code_ex_executi_7d939e_idx'),
        ),
        migrations.AddIndex(
            model_name='codeexecutionlog',
            index=models.Index(fields=['submission'], name='jac_code_ex_submiss_3cdcae_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['difficulty_level'], name='jac_learnin_difficu_432d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_published'], name='jac_learnin_is_publ_0d4ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_featured'], name='jac_learnin_is_feat_804e85_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['created_at'], name='jac_learnin_created_d9f935_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['learning_path', 'order'], name='jac_module_learnin_fd0b30_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['difficulty_rating'], name='jac_module_difficu_fd908e_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_published'], name='jac_module_is_publ_612a54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('learning_path', 'order')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='jac_lesson_module__3293e6_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='jac_lesson_lesson__5e8afa_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_published'], name='jac_lesson_is_publ_ebeee4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AddIndex(
            model_name='learningrecommendation',
            index=models.Index(fields=['user', 'recommendation_type'], name='jac_learnin_user_id_8171ba_idx'),
        ),
        migrations.AddIndex(
            model_name='learningrecommendation',
            index=models.Index(fields=['user', 'is_dismissed', 'expires_at'], name='jac_learnin_user_id_03bfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['user', 'status'], name='jac_code_su_user_id_c9158b_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['language'], name='jac_code_su_languag_36ff49_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['submission_id'], name='jac_code_su_submiss_a25480_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user', 'assessment'], name='jac_assessm_user_id_a6d401_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['status', 'started_at'], name='jac_assessm_status_390513_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['assessment', 'attempt_number'], name='jac_assessm_assessm_904d22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentattempt',
            unique_together={('user', 'assessment', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_type'], name='jac_assessm_assessm_6fae20_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['difficulty_level'], name='jac_assessm_difficu_a4a18e_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['is_published'], name='jac_assessm_is_publ_0b6de4_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['created_at'], name='jac_assessm_created_612fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='pathrating',
            index=models.Index(fields=['learning_path', 'rating'], name='jac_path_ra_learnin_df221d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pathrating',
            unique_together={('user', 'learning_path')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['assessment'], name='jac_questio_assessm_741f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='jac_questio_questio_f7256f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty_level'], name='jac_questio_difficu_ea66f5_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='jac_questio_created_21b886_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['assessment', 'order'], name='jac_assessm_assessm_7e2636_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['difficulty_level'], name='jac_assessm_difficu_735ae4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestion',
            unique_together={('assessment', 'question')},
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'unlocked_at'], name='jac_user_ac_user_id_89740a_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['achievement'], name='jac_user_ac_achieve_db3d30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='userassessmentresult',
            index=models.Index(fields=['user', 'assessment'], name='jac_user_as_user_id_9b2e33_idx'),
        ),
        migrations.AddIndex(
            model_name='userassessmentresult',
            index=models.Index(fields=['is_completed', 'best_score'], name='jac_user_as_is_comp_11312f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userassessmentresult',
            unique_together={('user', 'assessment')},
        ),
        migrations.AddIndex(
            model_name='userlearningpath',
            index=models.Index(fields=['user', 'status'], name='jac_user_le_user_id_f56575_idx'),
        ),
        migrations.AddIndex(
            model_name='userlearningpath',
            index=models.Index(fields=['status', 'last_activity_at'], name='jac_user_le_status_a5b55f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlearningpath',
            unique_together={('user', 'learning_path')},
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['user', 'status'], name='jac_user_mo_user_id_629892_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['module', 'status'], name='jac_user_mo_module__44df0c_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['status', 'last_activity_at'], name='jac_user_mo_status_c4fce7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermoduleprogress',
            unique_together={('user', 'module')},
        ),
    ]
