# Generated by Django 5.2.8 on 2025-11-24 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('completion', 'Completion'), ('performance', 'Performance'), ('streak', 'Streak'), ('skill', 'Skill'), ('engagement', 'Engagement'), ('collaboration', 'Collaboration')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('requirements', models.JSONField(default=dict, help_text='Requirements to unlock this achievement')),
                ('icon', models.CharField(blank=True, help_text='Icon URL or name', max_length=200)),
                ('badge_color', models.CharField(default='blue', help_text='CSS color class', max_length=20)),
                ('unlock_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jac_achievements',
                'ordering': ['achievement_type', 'rarity', 'name'],
                'indexes': [models.Index(fields=['achievement_type'], name='jac_achieve_achieve_08476f_idx'), models.Index(fields=['rarity'], name='jac_achieve_rarity_ee6d1b_idx'), models.Index(fields=['is_active'], name='jac_achieve_is_acti_c20f7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Examination'), ('assignment', 'Assignment'), ('project', 'Project'), ('practical', 'Practical Test')], default='quiz', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed')),
                ('passing_score', models.FloatField(default=70.0, help_text='Minimum score to pass (percentage)')),
                ('is_published', models.BooleanField(default=False)),
                ('average_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='learning.module')),
            ],
            options={
                'db_table': 'jac_assessment',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(default=100.0)),
                ('passing_score', models.FloatField(default=70.0)),
                ('is_passed', models.BooleanField(default=False)),
                ('time_spent', models.DurationField(default=0)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('answers', models.JSONField(default=dict, help_text='User answers for each question')),
                ('feedback', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.assessment')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='learning.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jac_assessment_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('lesson_type', models.CharField(choices=[('text', 'Text Lesson'), ('video', 'Video Lesson'), ('interactive', 'Interactive Content'), ('code_tutorial', 'Code Tutorial'), ('quiz', 'Quiz')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Lesson content in markdown or HTML')),
                ('code_example', models.TextField(blank=True, help_text='Code examples for this lesson')),
                ('quiz_questions', models.JSONField(blank=True, default=list, help_text='Quiz questions data')),
                ('interactive_demo', models.JSONField(blank=True, default=dict, help_text='Interactive demo configuration')),
                ('video_url', models.URLField(blank=True, help_text='URL to lesson video')),
                ('audio_url', models.URLField(blank=True, help_text='URL to lesson audio')),
                ('resources', models.JSONField(blank=True, default=list, help_text='Additional resources for this lesson')),
                ('is_published', models.BooleanField(default=False)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.module')),
            ],
            options={
                'db_table': 'jac_lesson',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('code', 'Code Challenge'), ('drag_drop', 'Drag and Drop')], default='multiple_choice', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('points', models.FloatField(default=1.0, help_text='Points awarded for correct answer')),
                ('question_options', models.JSONField(blank=True, default=list, help_text='Answer options for multiple choice questions')),
                ('correct_answer', models.JSONField(blank=True, default=dict, help_text='Correct answer data')),
                ('code_template', models.TextField(blank=True, help_text='Code template for coding questions')),
                ('test_cases', models.JSONField(blank=True, default=list, help_text='Test cases for code validation')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the correct answer')),
                ('hints', models.JSONField(blank=True, default=list, help_text='Hints to help users answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='learning.assessment')),
            ],
            options={
                'db_table': 'jac_question',
                'ordering': ['assessment', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('points', models.FloatField(default=1.0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_text_override', models.TextField(blank=True, help_text='Override default question text for this assessment')),
                ('options_override', models.JSONField(blank=True, default=list, help_text='Override default options for multiple choice')),
                ('correct_answer_override', models.JSONField(blank=True, default=list, help_text='Override correct answer')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('correct_attempts', models.PositiveIntegerField(default=0)),
                ('average_time', models.FloatField(default=0.0, help_text='Average time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='learning.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_links', to='learning.question')),
            ],
            options={
                'db_table': 'jac_assessment_questions',
                'ordering': ['assessment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(default=dict, help_text='Context when achievement was unlocked')),
                ('progress_at_unlock', models.JSONField(default=dict, help_text='User progress at time of unlock')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='learning.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jac_user_achievements',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('best_score', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('passed_attempts', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.DurationField(default=0)),
                ('first_attempt_score', models.FloatField(blank=True, null=True)),
                ('last_attempt_score', models.FloatField(blank=True, null=True)),
                ('improvement_rate', models.FloatField(default=0.0)),
                ('first_attempt_date', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_date', models.DateTimeField(blank=True, null=True)),
                ('passed_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='learning.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jac_user_assessment_results',
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_type'], name='jac_assessm_assessm_6fae20_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['difficulty_level'], name='jac_assessm_difficu_a4a18e_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['is_published'], name='jac_assessm_is_publ_0b6de4_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['created_at'], name='jac_assessm_created_612fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user', 'assessment'], name='jac_assessm_user_id_a6d401_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['status', 'started_at'], name='jac_assessm_status_390513_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['assessment', 'attempt_number'], name='jac_assessm_assessm_904d22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentattempt',
            unique_together={('user', 'assessment', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='jac_lesson_module__3293e6_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='jac_lesson_lesson__5e8afa_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_published'], name='jac_lesson_is_publ_ebeee4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['assessment'], name='jac_questio_assessm_741f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='jac_questio_questio_f7256f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty_level'], name='jac_questio_difficu_ea66f5_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='jac_questio_created_21b886_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['assessment', 'order'], name='jac_assessm_assessm_7e2636_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['difficulty_level'], name='jac_assessm_difficu_735ae4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestion',
            unique_together={('assessment', 'question')},
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'unlocked_at'], name='jac_user_ac_user_id_89740a_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['achievement'], name='jac_user_ac_achieve_db3d30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='userassessmentresult',
            index=models.Index(fields=['user', 'assessment'], name='jac_user_as_user_id_9b2e33_idx'),
        ),
        migrations.AddIndex(
            model_name='userassessmentresult',
            index=models.Index(fields=['is_completed', 'best_score'], name='jac_user_as_is_comp_11312f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userassessmentresult',
            unique_together={('user', 'assessment')},
        ),
    ]
