# Generated by Django 5.2.8 on 2025-11-24 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_add_missing_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Examination'), ('assignment', 'Assignment'), ('project', 'Project'), ('practical', 'Practical Test')], default='quiz', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed')),
                ('passing_score', models.FloatField(default=70.0, help_text='Minimum score to pass (percentage)')),
                ('is_published', models.BooleanField(default=False)),
                ('average_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jac_assessment',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('lesson_type', models.CharField(choices=[('text', 'Text Lesson'), ('video', 'Video Lesson'), ('interactive', 'Interactive Content'), ('code_tutorial', 'Code Tutorial'), ('quiz', 'Quiz')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Lesson content in markdown or HTML')),
                ('code_example', models.TextField(blank=True, help_text='Code examples for this lesson')),
                ('quiz_questions', models.JSONField(blank=True, default=list, help_text='Quiz questions data')),
                ('interactive_demo', models.JSONField(blank=True, default=dict, help_text='Interactive demo configuration')),
                ('video_url', models.URLField(blank=True, help_text='URL to lesson video')),
                ('audio_url', models.URLField(blank=True, help_text='URL to lesson audio')),
                ('resources', models.JSONField(blank=True, default=list, help_text='Additional resources for this lesson')),
                ('is_published', models.BooleanField(default=False)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jac_lesson',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('code', 'Code Challenge'), ('drag_drop', 'Drag and Drop')], default='multiple_choice', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('points', models.FloatField(default=1.0, help_text='Points awarded for correct answer')),
                ('question_options', models.JSONField(blank=True, default=list, help_text='Answer options for multiple choice questions')),
                ('correct_answer', models.JSONField(blank=True, default=dict, help_text='Correct answer data')),
                ('code_template', models.TextField(blank=True, help_text='Code template for coding questions')),
                ('test_cases', models.JSONField(blank=True, default=list, help_text='Test cases for code validation')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the correct answer')),
                ('hints', models.JSONField(blank=True, default=list, help_text='Hints to help users answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jac_question',
                'ordering': ['assessment', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['achievement_type', 'rarity', 'name']},
        ),
        migrations.AlterModelOptions(
            name='assessmentattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='assessmentquestion',
            options={'ordering': ['assessment', 'order']},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-unlocked_at']},
        ),
        migrations.RenameIndex(
            model_name='achievement',
            new_name='jac_achieve_achieve_08476f_idx',
            old_name='jac_achie_achievem_e7c9b8_idx',
        ),
        migrations.RenameIndex(
            model_name='achievement',
            new_name='jac_achieve_rarity_ee6d1b_idx',
            old_name='jac_achie_rarity_5f52e5_idx',
        ),
        migrations.RenameIndex(
            model_name='achievement',
            new_name='jac_achieve_is_acti_c20f7e_idx',
            old_name='jac_achie_is_acti_d40c8e_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentattempt',
            new_name='jac_assessm_user_id_a6d401_idx',
            old_name='jac_assess_user_id_assessment__31e7d8_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentattempt',
            new_name='jac_assessm_status_390513_idx',
            old_name='jac_assess_status_started__22c6c6_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentattempt',
            new_name='jac_assessm_assessm_904d22_idx',
            old_name='jac_assess_assessmen_attempt__3b3b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentquestion',
            new_name='jac_assessm_assessm_7e2636_idx',
            old_name='jac_assess_assessmen_order_c2bd15_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentquestion',
            new_name='jac_assessm_difficu_735ae4_idx',
            old_name='jac_assess_difficul_6e3c49_idx',
        ),
        migrations.RenameIndex(
            model_name='userachievement',
            new_name='jac_user_ac_user_id_89740a_idx',
            old_name='jac_userac_user_id_unlocke_7aed4a_idx',
        ),
        migrations.RenameIndex(
            model_name='userachievement',
            new_name='jac_user_ac_achieve_db3d30_idx',
            old_name='jac_userac_achievem_a7a43b_idx',
        ),
        migrations.RenameIndex(
            model_name='userassessmentresult',
            new_name='jac_user_as_user_id_9b2e33_idx',
            old_name='jac_useras_user_id_assessm_7c84a1_idx',
        ),
        migrations.RenameIndex(
            model_name='userassessmentresult',
            new_name='jac_user_as_is_comp_11312f_idx',
            old_name='jac_useras_is_comp_be5c89_idx',
        ),
    ]
