# Generated by Django 5.2.8 on 2025-11-24 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_achievement_assessment_assessmentattempt_lesson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentattempt',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_assessment_attempts', to='learning.module'),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_assessment_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userassessmentresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_assessment_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
