# JAC Interactive Learning Platform - Core backend implementation by Cavin Otieno

# Generated by Django 5.2.8 on 2025-11-25 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jac_execution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexecution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codeexecutionsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executiontemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
