# JAC Interactive Learning Platform - Core backend implementation by Cavin Otieno

# Generated by Django 5.2.8 on 2025-11-25 17:09

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Examination'), ('assignment', 'Assignment'), ('project', 'Project'), ('practical', 'Practical Test')], default='quiz', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed')),
                ('passing_score', models.FloatField(default=70.0, help_text='Minimum score to pass (percentage)')),
                ('is_published', models.BooleanField(default=False)),
                ('average_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'assessment_app_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('attempt_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(default=60)),
                ('score', models.FloatField(blank=True, help_text='Final score as percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_score', models.FloatField(default=100.0)),
                ('passing_score', models.FloatField(default=70.0)),
                ('answers', models.JSONField(default=dict, help_text='User answers to questions')),
                ('feedback', models.JSONField(default=dict, help_text='Detailed feedback for each question')),
            ],
            options={
                'verbose_name': 'Assessment Attempt',
                'verbose_name_plural': 'Assessment Attempts',
                'db_table': 'assessment_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('question_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('code_question', 'Code Question'), ('essay', 'Essay')], default='multiple_choice', max_length=30)),
                ('options', models.JSONField(default=list, help_text='Options for multiple choice questions')),
                ('correct_answer', models.TextField(help_text='Correct answer for the question')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('points', models.FloatField(default=1.0, help_text='Points awarded for correct answer')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of question in assessment')),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization')),
                ('learning_objectives', models.JSONField(default=list, help_text='Learning objectives this question addresses')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active/available')),
                ('version', models.PositiveIntegerField(default=1, help_text='Question version for tracking changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment Question',
                'verbose_name_plural': 'Assessment Questions',
                'db_table': 'assessment_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAssessmentResult',
            fields=[
                ('result_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('result_type', models.CharField(choices=[('assessment', 'Single Assessment'), ('module', 'Module Assessment'), ('learning_path', 'Learning Path Assessment')], default='assessment', max_length=20)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('best_score', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('topics_covered', models.JSONField(default=list, help_text='Topics covered in assessments')),
                ('learning_objectives_met', models.JSONField(default=list, help_text='Learning objectives achieved')),
                ('average_time_minutes', models.FloatField(default=0.0, help_text='Average time spent per attempt in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Assessment Result',
                'verbose_name_plural': 'User Assessment Results',
                'db_table': 'user_assessment_results',
                'ordering': ['-updated_at'],
            },
        ),
    ]
