# Generated by Django 5.2.8 on 2025-11-24 17:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0003_alter_assessmentattempt_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('attempt_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(default=60)),
                ('score', models.FloatField(blank=True, help_text='Final score as percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_score', models.FloatField(default=100.0)),
                ('passing_score', models.FloatField(default=70.0)),
                ('answers', models.JSONField(default=dict, help_text='User answers to questions')),
                ('feedback', models.JSONField(default=dict, help_text='Detailed feedback for each question')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='learning.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Attempt',
                'verbose_name_plural': 'Assessment Attempts',
                'db_table': 'assessment_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('question_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('code_question', 'Code Question'), ('essay', 'Essay')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for multiple choice questions')),
                ('correct_answer', models.TextField(help_text='Correct answer or answer key')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('points', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('tags', models.JSONField(default=list, help_text='Topic tags for the question')),
                ('learning_objectives', models.JSONField(default=list, help_text='Learning objectives this question tests')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='learning.module')),
            ],
            options={
                'verbose_name': 'Assessment Question',
                'verbose_name_plural': 'Assessment Questions',
                'db_table': 'assessment_questions',
                'ordering': ['module', 'difficulty', 'created_at'],
                'unique_together': {('module', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UserAssessmentResult',
            fields=[
                ('result_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('result_type', models.CharField(choices=[('module_completion', 'Module Completion'), ('overall_performance', 'Overall Performance'), ('topic_mastery', 'Topic Mastery'), ('progress_tracking', 'Progress Tracking')], max_length=25)),
                ('total_attempts', models.IntegerField(default=0)),
                ('best_score', models.FloatField(blank=True, null=True)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('average_time_minutes', models.FloatField(blank=True, null=True)),
                ('questions_attempted', models.JSONField(default=dict)),
                ('topics_covered', models.JSONField(default=list)),
                ('learning_objectives_met', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='learning.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Assessment Result',
                'verbose_name_plural': 'User Assessment Results',
                'db_table': 'user_assessment_results',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'module', 'result_type')},
            },
        ),
    ]
