# JAC Interactive Learning Platform - Core backend implementation by Cavin Otieno

# Generated by Django 5.2.8 on 2025-11-25 17:09

import datetime
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept_a', models.CharField(help_text='First concept in the relationship', max_length=200)),
                ('concept_b', models.CharField(help_text='Second concept in the relationship', max_length=200)),
                ('relation_type', models.CharField(choices=[('inherits', 'Inheritance - Concept A inherits from B'), ('implements', 'Implementation - A implements B'), ('depends', 'Dependency - A depends on B'), ('conflicts', 'Conflict - A conflicts with B'), ('complements', 'Complement - A complements B'), ('alternatives', 'Alternative - A is alternative to B')], max_length=20)),
                ('domain', models.CharField(help_text='Domain this relationship applies to', max_length=100)),
                ('description', models.TextField(help_text='Explanation of the relationship')),
                ('confidence_score', models.FloatField(default=0.8, help_text='Confidence score for this relationship (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'concept_relation',
                'ordering': ['domain', 'relation_type', 'concept_a'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('prerequisite', 'Prerequisite - Must learn before'), ('related', 'Related - Connected concepts'), ('example', 'Example - Shows application of'), ('depends_on', 'Depends On - Requires understanding of'), ('leads_to', 'Leads To - Next logical step'), ('contradicts', 'Contradicts - Opposite concepts'), ('similar_to', 'Similar To - Related concepts'), ('part_of', 'Part Of - Component of larger concept'), ('contains', 'Contains - Includes sub-concepts')], max_length=20)),
                ('strength', models.CharField(choices=[('weak', 'Weak Connection'), ('moderate', 'Moderate Connection'), ('strong', 'Strong Connection'), ('essential', 'Essential Connection')], default='moderate', max_length=20)),
                ('curve_points', models.JSONField(default=list, help_text='Control points for curved edges')),
                ('edge_weight', models.FloatField(default=1.0, help_text='Numerical weight for pathfinding algorithms')),
                ('description', models.TextField(blank=True, help_text='Description of the relationship')),
                ('examples', models.JSONField(blank=True, default=list, help_text='Examples illustrating this relationship')),
                ('traversal_count', models.IntegerField(default=0, help_text='Number of times this edge has been traversed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'knowledge_edge',
                'ordering': ['-traversal_count', 'edge_type'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Human-readable title for this knowledge node', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the knowledge concept')),
                ('node_type', models.CharField(choices=[('concept', 'Concept'), ('skill', 'Skill'), ('topic', 'Topic'), ('objective', 'Learning Objective'), ('assessment', 'Assessment'), ('resource', 'Learning Resource')], help_text='Type of knowledge node', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('x_position', models.FloatField(default=0.0, help_text='X coordinate for spatial positioning')),
                ('y_position', models.FloatField(default=0.0, help_text='Y coordinate for spatial positioning')),
                ('z_position', models.FloatField(default=0.0, help_text='Z coordinate for spatial positioning (layer)')),
                ('width', models.FloatField(default=1.0, help_text='Visual width in graph space')),
                ('height', models.FloatField(default=1.0, help_text='Visual height in graph space')),
                ('content_uri', models.CharField(blank=True, help_text='URI to related content', max_length=500)),
                ('jac_code', models.TextField(blank=True, help_text='Associated JAC code if applicable')),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text='List of learning objectives')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='Required prior knowledge')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0, help_text='Number of times this node has been viewed')),
            ],
            options={
                'db_table': 'knowledge_node',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LearningGraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the learning graph', max_length=200)),
                ('description', models.TextField(help_text='Comprehensive description of this learning graph')),
                ('graph_type', models.CharField(choices=[('course', 'Complete Course Curriculum'), ('module', 'Learning Module'), ('topic', 'Topic-Specific Graph'), ('skill_tree', 'Skill Development Tree'), ('concept_map', 'Concept Relationship Map'), ('assessment_path', 'Assessment Preparation Path')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft - Under Development'), ('active', 'Active - Available for Learning'), ('archived', 'Archived - No Longer Active'), ('review', 'In Review - Being Evaluated')], default='draft', max_length=20)),
                ('subject_area', models.CharField(help_text='Primary subject area', max_length=100)),
                ('target_audience', models.CharField(help_text='Intended audience level', max_length=100)),
                ('estimated_duration', models.DurationField(blank=True, help_text='Estimated time to complete', null=True)),
                ('layout_config', models.JSONField(default=dict, help_text='Configuration for graph visualization layout')),
                ('view_box', models.JSONField(default=dict, help_text='View box coordinates for graph display')),
                ('adaptive_rules', models.JSONField(default=dict, help_text='Rules for adaptive path generation')),
                ('difficulty_progression', models.JSONField(default=list, help_text='Configured difficulty progression path')),
                ('completion_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('average_completion_time', models.DurationField(blank=True, null=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('successful_completions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization and search')),
            ],
            options={
                'db_table': 'learning_graph',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LearningGraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether this edge must be traversed')),
                ('edge_priority', models.IntegerField(default=1, help_text='Priority for pathfinding (lower = higher priority)')),
                ('unlock_conditions', models.JSONField(default=dict, help_text='Conditions that must be met before this edge becomes available')),
                ('recommended_for', models.JSONField(default=list, help_text='User profiles this edge is recommended for')),
                ('custom_path', models.JSONField(default=list, help_text='Custom path points for this edge in this graph')),
            ],
            options={
                'db_table': 'learning_graph_edge',
                'ordering': ['display_order', 'edge_priority'],
            },
        ),
        migrations.CreateModel(
            name='LearningGraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, help_text='Order for sequential display')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this node is required for completion')),
                ('node_weight', models.FloatField(default=1.0, help_text='Importance weight in this graph')),
                ('custom_x', models.FloatField(blank=True, help_text='Custom X position for this node in this graph', null=True)),
                ('custom_y', models.FloatField(blank=True, help_text='Custom Y position for this node in this graph', null=True)),
                ('estimated_time', models.DurationField(blank=True, help_text='Time estimated to learn this node', null=True)),
                ('prerequisite_score', models.FloatField(default=0.0, help_text='Score required before this node becomes available', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'db_table': 'learning_graph_node',
                'ordering': ['display_order', 'knowledge_node__title'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title for this specific learning path', max_length=200)),
                ('adaptation_type', models.CharField(choices=[('static', 'Static - Fixed Path'), ('adaptive', 'Adaptive - Adjusts Based on Performance'), ('personalized', 'Personalized - Based on User Profile'), ('ai_generated', 'AI Generated - ML-Optimized')], default='adaptive', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active - Currently Following'), ('completed', 'Completed Successfully'), ('paused', 'Paused - Temporarily Stopped'), ('abandoned', 'Abandoned - No Longer Following'), ('failed', 'Failed - Unable to Complete')], default='active', max_length=20)),
                ('completed_nodes', models.JSONField(default=list, help_text='List of completed node IDs')),
                ('progress_percentage', models.FloatField(default=0.0, help_text='Overall completion percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_time_spent', models.DurationField(default=datetime.timedelta)),
                ('performance_metrics', models.JSONField(default=dict, help_text='User performance data for path adaptation')),
                ('adaptation_history', models.JSONField(default=list, help_text='History of path adaptations made')),
            ],
            options={
                'db_table': 'learning_path',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserKnowledgeState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mastery_level', models.CharField(choices=[('novice', 'Novice - No Understanding'), ('beginner', 'Beginner - Basic Awareness'), ('developing', 'Developing - Growing Understanding'), ('proficient', 'Proficient - Good Understanding'), ('expert', 'Expert - Deep Understanding')], default='novice', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence in mastery level (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('first_exposure', models.DateTimeField(default=django.utils.timezone.now, help_text='When user first encountered this concept')),
                ('last_reviewed', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time this concept was reviewed')),
                ('total_time_spent', models.DurationField(default=datetime.timedelta, help_text='Total time spent learning this concept')),
                ('assessment_scores', models.JSONField(default=list, help_text='Scores from assessments on this concept')),
                ('practice_attempts', models.IntegerField(default=0, help_text='Number of practice attempts')),
                ('successful_attempts', models.IntegerField(default=0, help_text='Number of successful practice attempts')),
                ('next_review_date', models.DateTimeField(blank=True, help_text='Next scheduled review for spaced repetition', null=True)),
                ('review_interval', models.DurationField(default=datetime.timedelta(days=1), help_text='Current review interval')),
                ('learning_velocity', models.FloatField(default=0.0, help_text='Rate of learning progress for this concept')),
                ('difficulty_adjustment', models.FloatField(default=0.0, help_text='Difficulty adjustment factor based on performance')),
            ],
            options={
                'db_table': 'user_knowledge_state',
                'ordering': ['user', 'knowledge_node__title'],
            },
        ),
    ]
