# Generated by Django 5.2.8 on 2025-11-25 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_graph', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptrelation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeedge',
            name='source_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='knowledge_graph.knowledgenode'),
        ),
        migrations.AddField(
            model_name='knowledgeedge',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='knowledge_graph.knowledgenode'),
        ),
        migrations.AddField(
            model_name='conceptrelation',
            name='related_nodes',
            field=models.ManyToManyField(blank=True, help_text='Knowledge nodes that demonstrate this relationship', to='knowledge_graph.knowledgenode'),
        ),
        migrations.AddField(
            model_name='learninggraph',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learninggraphedge',
            name='knowledge_edge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_graph.knowledgeedge'),
        ),
        migrations.AddField(
            model_name='learninggraphedge',
            name='learning_graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_graph.learninggraph'),
        ),
        migrations.AddField(
            model_name='learninggraph',
            name='edges',
            field=models.ManyToManyField(blank=True, through='knowledge_graph.LearningGraphEdge', to='knowledge_graph.knowledgeedge'),
        ),
        migrations.AddField(
            model_name='learninggraphnode',
            name='knowledge_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_graph.knowledgenode'),
        ),
        migrations.AddField(
            model_name='learninggraphnode',
            name='learning_graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_graph.learninggraph'),
        ),
        migrations.AddField(
            model_name='learninggraph',
            name='nodes',
            field=models.ManyToManyField(blank=True, through='knowledge_graph.LearningGraphNode', to='knowledge_graph.knowledgenode'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='current_node',
            field=models.ForeignKey(blank=True, help_text='Node the user is currently working on', null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge_graph.knowledgenode'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='learning_graph',
            field=models.ForeignKey(help_text='Source learning graph', on_delete=django.db.models.deletion.CASCADE, to='knowledge_graph.learninggraph'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='user',
            field=models.ForeignKey(help_text='User following this learning path', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userknowledgestate',
            name='knowledge_node',
            field=models.ForeignKey(help_text='Knowledge concept being tracked', on_delete=django.db.models.deletion.CASCADE, to='knowledge_graph.knowledgenode'),
        ),
        migrations.AddField(
            model_name='userknowledgestate',
            name='user',
            field=models.ForeignKey(help_text='User whose knowledge state is being tracked', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['node_type'], name='knowledge_n_node_ty_05c361_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['difficulty_level'], name='knowledge_n_difficu_521fab_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['is_active'], name='knowledge_n_is_acti_0efc3f_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['x_position', 'y_position'], name='knowledge_n_x_posit_3cdb39_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeedge',
            index=models.Index(fields=['source_node'], name='knowledge_e_source__614086_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeedge',
            index=models.Index(fields=['target_node'], name='knowledge_e_target__8b8ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeedge',
            index=models.Index(fields=['edge_type'], name='knowledge_e_edge_ty_28df58_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeedge',
            index=models.Index(fields=['strength'], name='knowledge_e_strengt_5e4f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeedge',
            index=models.Index(fields=['is_active'], name='knowledge_e_is_acti_999e5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgeedge',
            unique_together={('source_node', 'target_node', 'edge_type')},
        ),
        migrations.AddIndex(
            model_name='conceptrelation',
            index=models.Index(fields=['relation_type'], name='concept_rel_relatio_e80e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptrelation',
            index=models.Index(fields=['domain'], name='concept_rel_domain_6a2392_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptrelation',
            index=models.Index(fields=['confidence_score'], name='concept_rel_confide_51e59c_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptrelation',
            index=models.Index(fields=['is_active'], name='concept_rel_is_acti_73b8ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptrelation',
            unique_together={('concept_a', 'concept_b', 'relation_type', 'domain')},
        ),
        migrations.AddIndex(
            model_name='learninggraphedge',
            index=models.Index(fields=['learning_graph'], name='learning_gr_learnin_51cc50_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggraphedge',
            index=models.Index(fields=['knowledge_edge'], name='learning_gr_knowled_069e78_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggraphedge',
            index=models.Index(fields=['display_order'], name='learning_gr_display_15e6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggraphedge',
            index=models.Index(fields=['edge_priority'], name='edge_priority_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learninggraphedge',
            unique_together={('learning_graph', 'knowledge_edge')},
        ),
        migrations.AddIndex(
            model_name='learninggraphnode',
            index=models.Index(fields=['learning_graph'], name='learning_gr_learnin_9ffbd8_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggraphnode',
            index=models.Index(fields=['knowledge_node'], name='learning_gr_knowled_05eb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggraphnode',
            index=models.Index(fields=['display_order'], name='learning_gr_display_28a350_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggraphnode',
            index=models.Index(fields=['is_mandatory'], name='learning_gr_is_mand_94d233_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learninggraphnode',
            unique_together={('learning_graph', 'knowledge_node')},
        ),
        migrations.AddIndex(
            model_name='learninggraph',
            index=models.Index(fields=['graph_type'], name='learning_gr_graph_t_956e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggraph',
            index=models.Index(fields=['status'], name='learning_gr_status_8af599_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggraph',
            index=models.Index(fields=['subject_area'], name='learning_gr_subject_17523d_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggraph',
            index=models.Index(fields=['target_audience'], name='learning_gr_target__c49c73_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggraph',
            index=models.Index(fields=['completion_rate'], name='learning_gr_complet_1fe285_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['user'], name='learning_pa_user_id_580102_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['learning_graph'], name='learning_pa_learnin_ac0d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['status'], name='learning_pa_status_119173_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['adaptation_type'], name='learning_pa_adaptat_669a41_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['progress_percentage'], name='learning_pa_progres_b55b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='userknowledgestate',
            index=models.Index(fields=['user'], name='user_knowle_user_id_f62386_idx'),
        ),
        migrations.AddIndex(
            model_name='userknowledgestate',
            index=models.Index(fields=['knowledge_node'], name='user_knowle_knowled_af48e4_idx'),
        ),
        migrations.AddIndex(
            model_name='userknowledgestate',
            index=models.Index(fields=['mastery_level'], name='user_knowle_mastery_9d2f63_idx'),
        ),
        migrations.AddIndex(
            model_name='userknowledgestate',
            index=models.Index(fields=['confidence_score'], name='user_knowle_confide_45c925_idx'),
        ),
        migrations.AddIndex(
            model_name='userknowledgestate',
            index=models.Index(fields=['next_review_date'], name='user_knowle_next_re_bb07ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userknowledgestate',
            unique_together={('user', 'knowledge_node')},
        ),
    ]
